### PR TITLE
Minor fix payment type

### PR DESCRIPTION
**Pull request by aomegax**
#### List of Changes
- replace not-empty annotation with not-null one
- fix field name
- generated swagger

#### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by jacopocarlini — CHANGES_REQUESTED** [review]
the changes are ok, but fix the test failures

**Comment by aomegax** [comment]
other changes needed

**Comment by aomegax** [comment]
- Modified response of createPaymentType
- Add check to the input of createPaymentType given a bad request if payment type list is empty
- Add and fix unit test

**Review by jacopocarlini — APPROVED** [review]
ok

**Pull request merged**
