### PR TITLE
[PAGOPA-666] Pagination of GET psp by channel 

### PR DESCRIPTION
**Pull request by jacopocarlini**
depends on https://github.com/pagopa/pagopa-infra/pull/775

#### List of Changes

- Pagination GET PSP by ChannelCode
- refactor `mapPaymentType` with channelCode

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jacopocarlini** [comment]
update_code

**Review by pasqualespica — APPROVED** [review]
LGTM fix PR desc including `"+ fix  mapPaymentType with channelCode"`

**Comment by jacopocarlini** [comment]
**Before merge wait the PR for FE**

**Comment by jacopocarlini** [comment]
update_code

**Pull request merged**
