### PR TITLE
[PAGOPA-723] Fix delete payment types

### PR DESCRIPTION
**Pull request by aomegax**
#### List of Changes
- fix delete payment type

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aomegax** [comment]
update_code

**Comment by aomegax** [comment]
update_code

**Comment by jacopocarlini** [comment]
update_code

**Comment by jacopocarlini** [comment]
It is too large to review. I trust you.

**Review by jacopocarlini — APPROVED** [review]

**Pull request merged**
