### PR TITLE
[PAGOPA-825] remove bundles by cdi

### PR DESCRIPTION
**Pull request by alessio-acitelli**
- depends on [PAGOPA-825 on afm-utils](https://github.com/pagopa/pagopa-afm-utils/pull/25)

#### List of Changes

- added call to afm utils API to remove bundles by cdi

#### Motivation and Context

- remove also the bundles when a cdi is deleted

#### How Has This Been Tested?

- Manual and JUnit test

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Comment by alessio-acitelli** [comment]
update_code

**Review by aomegax — APPROVED** [review]
👍

**Pull request merged**
